### ISSUE TITLE
implement expiration timer for BZs

### ISSUE THREAD

**Issue by miabbott** [coreos/triagebot#3]
I envision two types of timers we could support:

1. timer related to `NEEDINFO`

When we set `NEEDINFO` on a BZ, we expect the person who is asked for more information to reply in a timely manner.  Using the OCP BZ guidelines as an example, it is acceptable to close a BZ with `INSUFFICIENT_DATA` after 2 weeks with no additional information.

2. timer related to age of the BZ

If the BZ hasn't had any activity on it for a configurable amount of time (30d?  60d?) it is unlikely to be resolved, so we should just close it to keep our queue more manageable.

**Comment by bgilbert** [comment]
For now, implemented a button to enable a timer for type 1.  If we need more, we can revisit.
