### ISSUE TITLE
Add support for tracking Fedora packaging bugs from Bugzilla

### ISSUE THREAD

**Issue by travier** [coreos/triagebot#6]
Title says it all.

I'm sorry I always come up with new ideas for this one.

**Comment by bgilbert** [comment]
I'm not planning to re-add Bugzilla support.  Can we mirror them into Jira components, either in COS or in a new project?

**Comment by travier** [comment]
Good idea.

**Comment by travier** [comment]
Found https://issues.redhat.com/projects/FC. Asking around if we can mirror more components.

**Comment by travier** [comment]
Closing as we'll do it the Jira route.
